import Colors from "@/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  backgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  ambientGlow: {
    position: "absolute",
    top: -120,
    alignSelf: "center",
    width: 480,
    height: 380,
    borderRadius: 240,
    overflow: "hidden",
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    justifyContent: "center",
  },
  mainCard: {
    width: "100%",
    maxWidth: 400,
    alignSelf: "center",
  },
  brandHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 6,
    marginBottom: 20,
  },
  logoImage: {
    width: 28,
    height: 28,
    borderRadius: 7,
  },
  brandTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    letterSpacing: 0.3,
    fontFamily: "Inter_700Bold",
  },
  headerArea: {
    alignItems: "center",
    marginTop: 2,
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  titleText: {
    color: "#FFFFFF",
    fontSize: 26,
    lineHeight: 32,
    letterSpacing: -0.5,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
    marginBottom: 6,
  },
  subtitleText: {
    color: "rgba(255, 255, 255, 0.65)",
    fontSize: 13.5,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 19,
    maxWidth: 290,
  },
  socialRow: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
    marginBottom: 18,
  },
  socialPill: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  socialPillPressed: {
    opacity: 0.72,
    backgroundColor: "rgba(38, 225, 154, 0.14)",
  },
  socialPillText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 18,
  },
  dividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
  },
  dividerText: {
    color: "rgba(255, 255, 255, 0.45)",
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    marginHorizontal: 14,
  },
  inputsContainer: {
    gap: 13,
    marginBottom: 4,
  },
  fieldShell: {
    height: 54,
    borderRadius: 27,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.09)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  fieldShellFocused: {
    borderColor: Colors.primary,
    borderWidth: 1.5,
    backgroundColor: "rgba(38, 225, 154, 0.08)",
  },
  fieldInput: {
    flex: 1,
    height: "100%",
    color: "#FFFFFF",
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    paddingVertical: 0,
  },
  eyeBtn: {
    paddingLeft: 10,
    paddingVertical: 10,
  },
  forgotBtn: {
    alignSelf: "flex-end",
    marginTop: 4,
    marginBottom: 8,
    paddingVertical: 4,
  },
  forgotText: {
    color: Colors.primary,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  submitBtnWrap: {
    height: 54,
    borderRadius: 27,
    overflow: "hidden",
    marginTop: 12,
    marginBottom: 14,
    boxShadow: "0px 6px 16px rgba(38, 225, 154, 0.45)",
  },
  submitBtnGradient: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtnText: {
    color: "#03140C",
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    letterSpacing: -0.2,
  },
  btnPressed: {
    opacity: 0.85,
  },
  submitBtnDisabled: {
    opacity: 0.6,
  },
  switchPromptRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    marginBottom: 8,
  },
  switchPromptText: {
    color: "rgba(255, 255, 255, 0.55)",
    fontSize: 14,
    fontFamily: "Inter_400Regular",
  },
  switchPromptAction: {
    color: Colors.primary,
    fontSize: 14,
    fontFamily: "Inter_700Bold",
    marginLeft: 5,
  },
  guestBtn: {
    alignSelf: "center",
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginBottom: 6,
  },
  guestBtnText: {
    color: "rgba(38, 225, 154, 0.70)",
    fontSize: 12.5,
    fontFamily: "Inter_500Medium",
  },
  legalFooterContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 20,
    paddingBottom: 8,
  },
  legalLink: {
    color: "rgba(255, 255, 255, 0.40)",
    fontSize: 12,
    fontFamily: "Inter_400Regular",
  },
  legalDivider: {
    color: "rgba(255, 255, 255, 0.24)",
    fontSize: 12,
  },
});
