import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
  },
  keyboardView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: "center",
    paddingHorizontal: 18,
  },
  authCard: {
    width: "100%",
  },
  brandHeader: {
    alignItems: "center",
    marginBottom: 26,
  },
  logoContainer: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: "#121212",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  logoImage: {
    width: 42,
    height: 42,
  },
  heroTitle: {
    fontSize: 26,
    fontFamily: "Inter_700Bold",
    color: "#FFFFFF",
    letterSpacing: -0.5,
    textAlign: "center",
  },
  heroSubtitle: {
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    color: "rgba(255, 255, 255, 0.6)",
    letterSpacing: -0.2,
    textAlign: "center",
    marginTop: 4,
  },
  modeSwitcherWrap: {
    flexDirection: "row",
    backgroundColor: "#121212",
    borderRadius: 24,
    padding: 3,
    marginBottom: 22,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  modeSwitcherTab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
  },
  modeSwitcherTabActive: {
    backgroundColor: "#222222",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  modeSwitcherText: {
    fontSize: 13.5,
    fontFamily: "Inter_600SemiBold",
    color: "rgba(255, 255, 255, 0.5)",
  },
  modeSwitcherTextActive: {
    color: "#FFFFFF",
    fontFamily: "Inter_700Bold",
  },
  switchPromptRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 14,
    marginBottom: 4,
  },
  switchPromptText: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: "rgba(255, 255, 255, 0.55)",
  },
  switchPromptAction: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    color: "#FFFFFF",
    marginLeft: 5,
  },
  formContainer: {
    gap: 12,
    marginBottom: 18,
  },
  fieldShell: {
    height: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    backgroundColor: "#121212",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
  },
  fieldShellFocused: {
    borderColor: "rgba(255, 255, 255, 0.4)",
    backgroundColor: "#181818",
  },
  fieldIcon: {
    marginRight: 10,
  },
  fieldInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    paddingVertical: 0,
  },
  eyeBtn: {
    paddingLeft: 6,
  },
  forgotBtn: {
    alignSelf: "flex-end",
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  forgotText: {
    fontSize: 12,
    color: Colors.primary,
    fontFamily: "Inter_600SemiBold",
  },
  submitBtn: {
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  submitBtnDisabled: {
    opacity: 0.65,
  },
  submitBtnText: {
    fontSize: 14.5,
    fontFamily: "Inter_700Bold",
    color: "#000000",
  },
  btnPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.985 }],
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  dividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
  },
  dividerText: {
    fontSize: 12,
    color: "rgba(255,255,255,0.4)",
    marginHorizontal: 12,
    fontFamily: "Inter_500Medium",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  socialStack: {
    gap: 10,
    marginBottom: 20,
  },
  socialBtn: {
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  socialIcon: {
    marginRight: 8,
  },
  socialBtnText: {
    color: "#FFFFFF",
    fontSize: 13.5,
    fontFamily: "Inter_600SemiBold",
  },
  appleWrap: {
    width: "100%",
    height: 48,
  },
  appleNativeBtn: {
    width: "100%",
    height: 48,
  },
  guestBtn: {
    height: 46,
    borderRadius: 23,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  guestBtnText: {
    color: "rgba(255, 255, 255, 0.72)",
    fontSize: 13,
    fontFamily: "Inter_500Medium",
  },
  legalFooterContainer: {
    marginTop: 18,
    paddingTop: 8,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  legalText: {
    fontSize: 11.5,
    color: "rgba(255,255,255,0.42)",
    textAlign: "center",
    lineHeight: 17,
    paddingHorizontal: 12,
  },
  legalLink: {
    color: "rgba(255,255,255,0.75)",
    textDecorationLine: "underline",
    fontFamily: "Inter_600SemiBold",
  },
});
