import { StyleSheet } from "react-native";

export const DOWNLOADS_UI = {
  bg: "#10141a",
  card: "#181c22",
  cardHover: "#20242b",
  border: "rgba(255, 255, 255, 0.08)",
  text: "#dfe2eb",
  subtext: "#8e99a8",
  lowSurface: "#181c22",
  highSurface: "#262a31",
  primaryA: "#26e19a",
  primaryB: "#00b87b",
  error: "#ff5449",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DOWNLOADS_UI.bg,
  },
  mainWrap: {
    flex: 1,
  },
  headerRightContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  stickyPlayButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: DOWNLOADS_UI.primaryA,
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.3)",
  },
  stickyPlayButtonPressed: {
    transform: [{ scale: 0.94 }],
    opacity: 0.9,
  },
  tabBarWrap: {
    paddingHorizontal: 16,
    paddingTop: 6,
    paddingBottom: 8,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: DOWNLOADS_UI.card,
    borderRadius: 24,
    padding: 3,
    borderWidth: 1,
    borderColor: DOWNLOADS_UI.border,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
    borderRadius: 20,
  },
  tabBtnActive: {
    backgroundColor: DOWNLOADS_UI.primaryA,
  },
  tabBtnText: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 13,
    fontFamily: "Inter_500Medium",
  },
  tabBtnTextActive: {
    color: "#042115",
    fontFamily: "Inter_700Bold",
  },
  searchContainer: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 16,
  },
  searchInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DOWNLOADS_UI.lowSurface,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 40,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  searchPlaceholderText: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    marginLeft: 8,
  },
  heroSection: {
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  heroIconCard: {
    width: 96,
    height: 96,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
    boxShadow: "0 8px 16px rgba(38, 225, 154, 0.35)",
  },
  heroTitle: {
    color: DOWNLOADS_UI.text,
    fontSize: 26,
    fontFamily: "Inter_700Bold",
    letterSpacing: -0.5,
    textAlign: "center",
  },
  heroMeta: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    marginTop: 6,
    letterSpacing: 0.5,
    textAlign: "center",
  },
  actionSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: 8,
    marginBottom: 12,
  },
  storageBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "rgba(38, 225, 154, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(38, 225, 154, 0.2)",
  },
  storageBadgeText: {
    color: DOWNLOADS_UI.primaryA,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  rightActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  shuffleButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  shuffleButtonActive: {
    backgroundColor: "rgba(38, 225, 154, 0.12)",
  },
  shuffleButtonPressed: {
    transform: [{ scale: 0.92 }],
    opacity: 0.8,
  },
  playAllButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: DOWNLOADS_UI.primaryA,
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 4px 10px rgba(38, 225, 154, 0.35)",
  },
  playAllButtonPressed: {
    transform: [{ scale: 0.94 }],
    opacity: 0.9,
  },
  songListSpacer: {
    height: 8,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 120,
  },
  listContentEmpty: {
    flexGrow: 1,
  },
  emptyWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 60,
    paddingHorizontal: 32,
    gap: 12,
  },
  emptyTitle: {
    color: DOWNLOADS_UI.text,
    fontSize: 20,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
  },
  emptySubtitle: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 20,
  },
  browseBtn: {
    marginTop: 8,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    backgroundColor: DOWNLOADS_UI.primaryA,
  },
  browseBtnText: {
    color: "#042115",
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  searchModeContainer: {
    flex: 1,
    backgroundColor: DOWNLOADS_UI.bg,
  },
  searchModeHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  searchModeInputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: DOWNLOADS_UI.lowSurface,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 40,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  searchModeInput: {
    flex: 1,
    color: DOWNLOADS_UI.text,
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    marginLeft: 8,
    paddingVertical: 0,
  },
  searchModeCancelButton: {
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  searchModeCancelText: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 15,
    fontFamily: "Inter_500Medium",
  },
  searchModeListContent: {
    paddingTop: 8,
    paddingBottom: 120,
  },
  searchModeEmptyWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 80,
    paddingHorizontal: 32,
    gap: 12,
  },
  searchModeEmptyTitle: {
    color: DOWNLOADS_UI.text,
    fontSize: 18,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
  },
  searchModeEmptySubtitle: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    textAlign: "center",
    lineHeight: 20,
  },

  // Settings tab styles
  settingsScrollView: {
    flex: 1,
  },
  settingsScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  storageCard: {
    backgroundColor: DOWNLOADS_UI.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: DOWNLOADS_UI.border,
    marginBottom: 20,
  },
  storageTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  storageTextGroup: {
    flex: 1,
  },
  storageTitle: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  storageValue: {
    color: DOWNLOADS_UI.text,
    fontSize: 24,
    fontFamily: "Inter_700Bold",
    marginTop: 2,
  },
  storageIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(38, 225, 154, 0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  storageMetricsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#13171d",
    borderRadius: 10,
    paddingVertical: 10,
  },
  metricItem: {
    alignItems: "center",
    flex: 1,
  },
  metricNum: {
    color: DOWNLOADS_UI.text,
    fontSize: 16,
    fontFamily: "Inter_700Bold",
  },
  metricLabel: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  metricDivider: {
    width: 1,
    height: 20,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  sectionHeaderTitle: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  groupedCard: {
    backgroundColor: DOWNLOADS_UI.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: DOWNLOADS_UI.border,
    overflow: "hidden",
  },
  settingDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    marginHorizontal: 14,
  },
  qualityItemRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
  },
  qualityItemRowActive: {
    backgroundColor: "#1c222b",
  },
  qualityItemRowPressed: {
    backgroundColor: DOWNLOADS_UI.cardHover,
  },
  qualityTextCol: {
    flex: 1,
    paddingRight: 12,
  },
  qualityItemTitle: {
    color: DOWNLOADS_UI.text,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
  },
  qualityItemTitleActive: {
    color: DOWNLOADS_UI.primaryA,
  },
  qualityItemSub: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: DOWNLOADS_UI.subtext,
    alignItems: "center",
    justifyContent: "center",
  },
  radioCircleActive: {
    borderColor: DOWNLOADS_UI.primaryA,
  },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: DOWNLOADS_UI.primaryA,
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
  },
  settingInfo: {
    flex: 1,
    paddingRight: 12,
  },
  settingLabel: {
    color: DOWNLOADS_UI.text,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
  },
  settingDesc: {
    color: DOWNLOADS_UI.subtext,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    marginTop: 2,
  },
  dangerCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 84, 73, 0.08)",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 84, 73, 0.2)",
    marginTop: 4,
  },
  dangerCardPressed: {
    backgroundColor: "rgba(255, 84, 73, 0.16)",
  },
  dangerText: {
    color: DOWNLOADS_UI.error,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
  },
});
