import { StyleSheet } from "react-native";
import { IS_ANDROID, IS_IOS } from "@/constants/platform";
import Colors from "@/constants/colors";
import {
  PLAYER_SLIDER_TOUCH_HEIGHT,
  PLAYER_SLIDER_THUMB_SIZE,
  PLAYER_SLIDER_MINIMUM_TRACK_COLOR,
  PLAYER_SLIDER_MAXIMUM_TRACK_COLOR,
  PLAYER_SLIDER_THUMB_COLOR,
} from "@/lib/sliderUtils";
import { playerArtistStyles } from "./playerArtistStyles";
import { playerQueueStyles } from "./playerQueueStyles";

export const styles = StyleSheet.create({
  sheetContainer: {
    position: "absolute",
    zIndex: 998,
    overflow: "hidden",
  },
  contentWrap: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  playerSheetSurface: {
    flex: 1,
    backgroundColor: "transparent",
    overflow: "visible",
  },
  backdropOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.54)",
  },
  backgroundYoutubeContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    overflow: "hidden",
    zIndex: IS_ANDROID ? 0 : -1,
  },
  activeCardReanimatedContainer: {
    alignItems: "center",
    justifyContent: "center",
    zIndex: 99,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000000",
    overflow: "hidden",
  },
  backgroundColorWash: {
    opacity: 0.2,
  },
  lowerDarkBackdrop: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "transparent",
  },
  lowerDarkFade: {
    position: "absolute",
    left: 0,
    right: 0,
    top: -132,
    height: 132,
  },

  playerForeground: {
    flex: 1,
  },
  topBar: {
    height: 54,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  playerScroll: {
    flex: 1,
  },
  playerScrollContent: {
    paddingBottom: 20,
    position: "relative",
  },
  playerContent: {
    flexGrow: 0,
  },
  playerPrimaryStack: {
    flex: 1,
    justifyContent: "space-between",
  },
  playerActionStack: {
    flexGrow: 0,
  },
  headerIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  headerIconButtonPressed: {
    opacity: 0.58,
  },
  headerSideGroup: {
    width: 84,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerRightGroup: {
    justifyContent: "flex-end",
  },

  stickyHeaderContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 100,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
    position: "relative",
  },
  headerTitleWrap: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitleAbsolute: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  headerSongTitle: {
    color: "#FFFFFF",
    fontFamily: "Inter_700Bold",
    textAlign: "center",
  },
  headerSongArtist: {
    color: "rgba(255, 255, 255, 0.65)",
    fontSize: 11,
    fontFamily: "Inter_500Medium",
    textAlign: "center",
    marginTop: 1,
  },

  headerCaption: {
    color: Colors.subtext,
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.9,
    textTransform: "uppercase",
  },
  headerAlbum: {
    color: "#FFFFFF",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  artWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 0,
    marginTop: 6,
  },
  artCarousel: {
    width: "100%",
    overflow: "visible",
  },
  artCarouselContent: {
    alignItems: "center",
  },
  artCarouselTouch: {
    alignItems: "center",
    justifyContent: "center",
  },
  artCarouselCard: {
    alignSelf: "center",
  },
  artFrame: {
    borderRadius: 22,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  artFrameDefault: {
    borderRadius: 22,
  },
  youtubeArtFrame: {
    borderRadius: 22,
    backgroundColor: "#000000",
  },
  albumArt: {
    width: "100%",
    height: "100%",
  },
  albumArtLayer: {
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(10,14,20,0.92)",
  },
  albumArtParallax: {
    width: "100%",
    height: "100%",
  },
  albumFallback: {
    alignItems: "center",
    justifyContent: "center",
  },
  youtubeVideoFrame: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000000",
    overflow: "hidden",
  },
  youtubeDetailPlayer: {
    width: "100%",
    height: "100%",
    backgroundColor: "#000000",
    overflow: "hidden",
  },
  youtubeDetailIframe: {
    width: "100%",
    height: "100%",
    backgroundColor: "#000000",
  },
  youtubeDetailShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.18)",
  },
  youtubeDetailLoading: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.16)",
  },
  adCardContainer: {
    backgroundColor: "#11141a",
    overflow: "hidden",
    position: "relative",
  },
  adCardMedia: {
    width: "100%",
    height: "100%",
    backgroundColor: "#000000",
  },
  adCardOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(17, 20, 26, 0.82)",
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderTopWidth: 0.5,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  adCardTextWrap: {
    flex: 1,
    gap: 2,
  },
  adCardBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  adCardBadge: {
    backgroundColor: "rgba(38, 225, 154, 0.15)",
    borderWidth: 0.5,
    borderColor: "#26e19a",
    borderRadius: 3,
    paddingHorizontal: 3,
    paddingVertical: 1,
  },
  adCardBadgeText: {
    color: "#26e19a",
    fontSize: 7.5,
    fontFamily: "Inter_700Bold",
  },
  adCardHeadline: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    flexShrink: 1,
  },
  adCardBody: {
    color: "rgba(255, 255, 255, 0.5)",
    fontSize: 10,
    fontFamily: "Inter_400Regular",
  },
  adCardCtaButton: {
    color: "#10141a",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    backgroundColor: "#26e19a",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4.5,
    overflow: "hidden",
    textAlign: "center",
  },
  adBadgeOverlay: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 10,
    borderRadius: 12,
    borderWidth: 0.5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  adBadgeText: {
    fontSize: 9.5,
    fontFamily: "Inter_700Bold",
  },
  songBlock: {
    marginTop: 18,
    marginHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  songBlockCompact: {
    marginTop: 10,
  },
  songBlockArtwork: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  songTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  songDetailActions: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 2,
  },
  songDetailActionButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  songTitle: {
    color: Colors.text,
    fontSize: 25,
    lineHeight: 30,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0,
  },
  songTitleCompact: {
    fontSize: 23,
    lineHeight: 27,
  },
  songArtist: {
    marginTop: 2,
    color: Colors.subtext,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: "Inter_400Regular",
  },
  songArtistCompact: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 16,
  },
  likeButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    flexShrink: 0,
    overflow: "hidden",
  },

  spotifyProgressWrap: {
    marginTop: 14,
    marginHorizontal: 20,
    paddingHorizontal: 0,
    paddingVertical: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  playerSlider: {
    width: "100%",
    height: PLAYER_SLIDER_TOUCH_HEIGHT,
    marginVertical: 0,
    justifyContent: "center",
    position: "relative",
  },
  playerSliderDisabled: {
    opacity: 0.7,
  },
  playerSliderTrack: {
    width: "100%",
    height: 4,
    borderRadius: 999,
    backgroundColor: PLAYER_SLIDER_MAXIMUM_TRACK_COLOR,
    overflow: "hidden",
  },
  playerSliderFill: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    borderRadius: 999,
    backgroundColor: PLAYER_SLIDER_MINIMUM_TRACK_COLOR,
  },
  playerSliderThumb: {
    position: "absolute",
    left: 0,
    top: (PLAYER_SLIDER_TOUCH_HEIGHT - PLAYER_SLIDER_THUMB_SIZE) / 2,
    width: PLAYER_SLIDER_THUMB_SIZE,
    height: PLAYER_SLIDER_THUMB_SIZE,
    borderRadius: PLAYER_SLIDER_THUMB_SIZE / 2,
    backgroundColor: PLAYER_SLIDER_THUMB_COLOR,
  },
  spotifyTimeRow: {
    marginTop: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  spotifyTimeText: {
    color: "rgba(247,250,255,0.62)",
    fontSize: 11,
    lineHeight: 14,
    fontFamily: "Inter_500Medium",
    letterSpacing: 0,
  },

  controlsRow: {
    marginTop: 12,
    marginHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  controlsRowCompact: {
    marginTop: 0,
  },
  utilityControlButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
  },
  bottomUtilityRow: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bottomUtilityButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  playerDownloadButton: {
    width: 38,
    height: 38,
    padding: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  playingListSection: {
    alignSelf: "stretch",
    marginTop: 0,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  playingListSectionAmbient: {
    backgroundColor: "transparent",
  },
  roundIconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    position: "relative",
    flexShrink: 0,
    overflow: "hidden",
  },
  quickButtonPressed: {
    opacity: 0.58,
  },
  prevNextButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    position: "relative",
    flexShrink: 0,
    overflow: "hidden",
  },
  roundIconButtonActive: {
    borderColor: Colors.primary,
    backgroundColor: "rgba(37, 201, 231, 0.14)",
  },
  playButton: {
    width: 74,
    height: 74,
    borderRadius: 37,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F4F7FB",
    boxShadow: "none",
    flexShrink: 0,
    overflow: "hidden",
  },
  repeatOneBadge: {
    position: "absolute",
    bottom: 5,
    right: 7,
    color: Colors.primary,
    fontSize: 10,
    fontFamily: "Inter_700Bold",
  },
  emptyContainer: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  emptyText: {
    color: Colors.subtext,
    fontSize: 18,
    fontFamily: "Inter_500Medium",
  },
  emptyHint: {
    maxWidth: 280,
    color: Colors.inactive,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
    fontFamily: "Inter_500Medium",
  },
  emptyDevButton: {
    minHeight: 42,
    paddingHorizontal: 16,
    borderRadius: 21,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.primary,
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  emptyDevButtonText: {
    color: Colors.text,
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  emptyDevSecondaryButton: {
    minHeight: 42,
    paddingHorizontal: 16,
    borderRadius: 21,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  emptyDevSecondaryButtonText: {
    color: Colors.text,
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  emptyBackButton: {
    marginTop: 8,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  ...playerQueueStyles,
  ...playerArtistStyles,
});
