import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const styles = StyleSheet.create({
  authRouteFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.background,
  },
  iosMiniPlayerRoot: {
    position: "absolute",
    left: 19,
    right: 19,
    zIndex: 30,
  },
  iosMiniPlayerDockRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  iosMiniPlayerShell: {
    flex: 1,
    height: 50,
    overflow: "hidden",
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "#111317",
    boxShadow: "none",
  },
  iosMiniPlayerBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  iosMiniPlayerTopHairline: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  iosMiniPlayerRow: {
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 6,
    paddingVertical: 0,
  },
  iosMiniPlayerMain: {
    flex: 1,
    height: "100%",
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  iosMiniPlayerArtworkShell: {
    width: 50,
    height: "100%",
    padding: 5,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  iosMiniPlayerCover: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "transparent",
  },
  iosMiniPlayerCoverFallback: {
    alignItems: "center",
    justifyContent: "center",
  },
  iosMiniPlayerText: {
    flex: 1,
    minWidth: 0,
    marginLeft: 9,
    marginRight: 6,
    justifyContent: "center",
  },
  iosMiniPlayerTitle: {
    fontSize: 13.5,
    lineHeight: 17,
    fontFamily: "Inter_700Bold",
  },
  iosMiniPlayerArtist: {
    marginTop: 1,
    fontSize: 11,
    lineHeight: 14,
    fontFamily: "Inter_500Medium",
  },
  iosMiniPlayerMixSimpleContent: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  iosMiniPlayerMixCard: {
    width: "100%",
    height: "100%",
    borderRadius: 28,
    overflow: "hidden",
  },
  iosMiniPlayerMixFullImage: {
    width: "100%",
    height: "100%",
  },
  iosMiniPlayerMixFullImageMuted: {
    opacity: 0.74,
  },
  iosMiniPlayerMixHeroFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  iosMiniPlayerMixEqOverlay: {
    position: "absolute",
    right: 5,
    bottom: 5,
    height: 15,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 2,
    borderRadius: 9,
    paddingHorizontal: 4,
    paddingVertical: 2,
    backgroundColor: "rgba(8,8,10,0.42)",
  },
  iosMiniPlayerMixEqBar: {
    width: 2.4,
    height: 10,
    borderRadius: 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.96)",
    transform: [{ scaleY: 0.4 }],
  },
  iosMiniPlayerMixGrid: {
    width: "100%",
    height: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: "#1a1a1a",
  },
  iosMiniPlayerMixGridCell: {
    width: "50%",
    height: "50%",
    overflow: "hidden",
    backgroundColor: "#0a0a0a",
    borderWidth: 0.5,
    borderColor: "rgba(255,255,255,0.08)",
  },
  iosMiniPlayerMixGridImage: {
    width: "100%",
    height: "100%",
    opacity: 0.8,
  },
  iosMiniPlayerMixGridFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  iosMiniPlayerMixGridMore: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  iosMiniPlayerMixGridMoreText: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
  },
  iosMiniPlayerControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginLeft: 0,
    flexShrink: 0,
  },
  iosMiniPlayerButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  iosMiniPlayerPrimaryButton: {
    backgroundColor: "#FFFFFF",
    borderRadius: 21,
    borderWidth: 0,
  },
  iosMiniPlayerSecondaryButton: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.12)",
  },
  miniButtonPressed: {
    opacity: 0.9,
  },
  iosMiniPlayerInlineMixBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    overflow: "hidden",
    marginRight: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "transparent",
  },
  iosMiniPlayerSideActions: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    marginLeft: 0,
  },
  iosMiniPlayerSideActionBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 0,
    backgroundColor: "transparent",
  },
  iosMiniPlayerSideActionBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  iosMiniPlayerProgressTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 1.5,
    borderRadius: 0,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  iosMiniPlayerProgressFill: {
    height: "100%",
    borderRadius: 999,
  },
  wrapper: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 40,
    alignItems: "center",
  },
  wrapperHidden: {
    opacity: 0,
  },
  container: {
    width: "100%",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: "hidden",
  },
  containerIOS: {},
  containerNavOnly: {},
  containerNavOnlyIOS: {},
  glassLayer: {
    ...StyleSheet.absoluteFillObject,
  },

  playerSection: {
    backgroundColor: "#0A0A0C",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
    overflow: "hidden",
  },
  playerSectionIOS: {
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  miniBannerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 3.5,
    minHeight: 22,
    backgroundColor: "transparent",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255, 255, 255, 0.14)",
  },
  miniBannerRowPressed: {
    opacity: 0.75,
  },
  miniBannerContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    minWidth: 0,
  },
  miniBannerIcon: {
    marginRight: 6.5,
  },
  miniBannerText: {
    flex: 1,
    fontSize: 11.5,
    fontFamily: "Inter_600SemiBold",
    color: "#E2E8F0",
    letterSpacing: -0.2,
  },
  miniBannerDots: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3.5,
    marginRight: 6,
    marginLeft: 6,
  },
  miniBannerDot: {
    width: 3.5,
    height: 3.5,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.28)",
  },
  miniBannerDotActive: {
    width: 8,
    borderRadius: 2,
    backgroundColor: "#FFFFFF",
  },

  playerTopEdge: {
    position: "absolute",
    top: 0,
    left: 8,
    right: 8,
    height: 1,
    backgroundColor: "rgba(38,225,154,0.28)",
    opacity: 0.32,
  },
  playerCornerAccentLeft: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 10,
    height: 7,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderTopLeftRadius: 10,
    opacity: 0.36,
  },
  playerCornerAccentRight: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 10,
    height: 7,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderTopRightRadius: 10,
    opacity: 0.36,
  },
  playerProgressTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 2,
    borderRadius: 0,
    overflow: "hidden",
    backgroundColor: "rgba(223, 226, 235, 0.18)",
  },
  playerProgressFill: {
    height: 2,
    backgroundColor: "#FFFFFF",
  },

  // Mix chip — compact black pill, right of song title
  mixChipWrap: {
    flexShrink: 0,
  },
  mixChip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#000",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    flexShrink: 0,
    marginRight: 6,
    overflow: "hidden",
    paddingHorizontal: 7,
  },
  mixChipDragging: {
    borderColor: "rgba(255,255,255,0.42)",
  },
  mixChipDeleteReady: {
    borderColor: "rgba(255, 92, 92, 0.85)",
    backgroundColor: "rgba(35, 2, 2, 0.94)",
  },
  mixChipAvatars: {
    flexDirection: "row",
    alignItems: "center",
  },
  mixChipAvatar: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#000",
    backgroundColor: "#1a1a1a",
  },
  mixTrashDock: {
    position: "absolute",
    left: 60,
    top: "50%",
    width: 32,
    height: 32,
    marginTop: -16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    backgroundColor: "rgba(15,15,15,0.96)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    boxShadow: "0 8px 24px rgba(0,0,0,0.22)",
  },
  mixTrashDockActive: {
    borderColor: "rgba(255, 92, 92, 0.9)",
    backgroundColor: "rgba(82, 16, 16, 0.95)",
  },
  playerRow: {
    height: 50,
    paddingLeft: 10,
    paddingRight: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  playerLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  coverWrap: {
    width: 40,
    height: 40,
    overflow: "hidden",
    borderRightWidth: 0,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  cover: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "transparent",
  },
  coverFallback: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  songInfo: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
    marginRight: 8,
    justifyContent: "center",
  },
  songInfoDuringMixDrag: {
    opacity: 0.38,
  },
  songTitle: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    lineHeight: 16,
  },
  songArtist: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    lineHeight: 14,
    marginTop: 1,
  },
  playerControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginLeft: 4,
    marginRight: 2,
    flexShrink: 0,
  },
  iconButton: {
    minWidth: 34,
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 17,
    backgroundColor: "transparent",
  },
  iconButtonPrimary: {
    backgroundColor: "#FFFFFF",
    borderRadius: 17,
    borderWidth: 0,
  },
  navContent: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    backgroundColor: "transparent",
    overflow: "hidden",
    position: "relative",
    borderTopWidth: 0,
    borderTopColor: "rgba(255, 255, 255, 0.09)",
  },
  navContentIOS: {
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  navContentNavOnly: {},

  navItemAnimWrap: {
    flex: 1,
    minWidth: 0,
    height: 50,
  },
  navIconWrap: {
    width: 44,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  navIconLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  navItem: {
    width: "100%",
    height: 50,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    zIndex: 1,
  },
  navItemPressed: {
    opacity: 0.9,
  },
  navItemIOS: {
    borderRadius: 12,
    marginHorizontal: 0,
  },
  navItemActive: {
    backgroundColor: "transparent",
  },
  navItemIOSActive: {
    backgroundColor: "transparent",
  },
  navLabel: {
    fontSize: 10,
    lineHeight: 12,
    includeFontPadding: false,
    fontFamily: "Inter_500Medium",
    textAlign: "center",
    color: "rgba(255, 255, 255, 0.65)",
    letterSpacing: -0.1,
  },
  navLabelIOS: {
    fontFamily: "Inter_600SemiBold",
    color: "rgba(235, 235, 245, 0.65)",
    letterSpacing: -0.1,
  },
  navLabelActive: {
    color: Colors.text,
  },
});
